
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate

# Enable telegram bot
telegram_bot:
  - platform: broadcast
    api_key: <token>
    allowed_chat_ids:
      - 10944908 # example id of a user
#      - -987654321  # example id of a group, starts with a -

# enable communication with ARLO devices
# arlo:
#   username: <username>
#   password: <password>

sensor:
  # enable DSMR sensor
  - platform: dsmr
    host: 192.168.178.44
    port: 2001
    dsmr_version: 5

  # enable rest endpoint for ethnode with our account
  - platform: rest
    name: ethnode_get_balance
    resource: http://192.168.178.39:5000/get_my_balance

  - platform: rest
    resource: http://ip.jsontest.com
    name: External IP
    value_template: '{{ value_json.ip }}'