#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable telegram bot
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - 10944908 # example id of a user
#      - -987654321  # example id of a group, starts with a -

# enable communication with ARLO devices
# arlo:
#   username: <username>
#   password: <password>

sensor:

  - platform: fritzbox_netmonitor
    # name: Fritzbox

  # enable DSMR sensor
  - platform: dsmr
    host: 192.168.178.44
    port: 2001
    dsmr_version: 5

  # enable rest endpoint for ethnode with our account
  # - platform: rest
  #   name: ethnode_get_balance
  #   resource: http://192.168.178.39:5000/get_my_balance

  - platform: mqtt
    name: mqtt_bathroom_humidity
    state_topic: "bathroom/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_living_humidity
    state_topic: "living/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_bathroom_temperature
    state_topic: "bathroom/temperature"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_living_temperature
    state_topic: "living/temperature"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_fan_speed
    state_topic: 'fan/speed'

  - platform: mqtt
    name: mqtt_heater_status
    state_topic: 'heater/status'