# watch_doorbell:
#   module: watch_doorbell
#   class: WatchDoorbell

watch_fan:
  module: watch_fan
  class: WatchFan

watch_thermostat:
  module: watch_thermostat
  class: WatchThermostat

watch_night_heater:
  module: watch_night_heater
  class: WatchNightHeater

# watch_garden_light:
#   module: watch_garden_light
#   class: WatchLight

# watch_christmas_light:
#   module: watch_christmas_light
#   class: WatchLight