#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

sensor:
  
  - platform: mqtt
    name: mqtt_bathroom_humidity
    state_topic: "bathroom/humidity"