watch_doorbell:
  module: watch_doorbell
  class: WatchDoorbell

watch_fan:
  module: watch_fan
  class: WatchFan

watch_thermostat:
  module: watch_thermostat
  class: WatchThermostat

watch_light:
  module: watch_light
  class: WatchLight