#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml

# frontend:
#   themes: !include themes.yaml

# Devices & Entities
sensor: !include sensor.yaml
switch: !include switch.yaml
climate: !include climate.yaml

# helpers
# input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml

# other fancy configs
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable telegram bot
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - 10944908 # example id of a user
#      - -987654321  # example id of a group, starts with a -

# enable communication with ARLO devices
# arlo:
#   username: <username>
#   password: <password>

rest_command:
  set_fan_speed_1:
    url: 'http://192.168.178.29:5000/set_speed?speed=1'

  set_fan_speed_2:
    url: 'http://192.168.178.29:5000/set_speed?speed=2'

  set_fan_speed_3:
    url: 'http://192.168.178.29:5000/set_speed?speed=3'

  set_fan_speed_0:
    url: 'http://192.168.178.29:5000/set_speed?speed=0'

  set_fan_speed_auto:
    url: 'http://192.168.178.29:5000/set_speed?speed=9'