#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#################################################################
## Manual entities
#################################################################
sensor: !include sensor.yaml
switch: !include switch.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable telegram bot
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - 10944908 # example id of a user
#      - -987654321  # example id of a group, starts with a -

# enable communication with ARLO devices
# arlo:
#   username: <username>
#   password: <password>

climate:
  - platform: generic_thermostat
    name: Thermostat
    heater: switch.mqtt_heater
    target_sensor: sensor.mqtt_living_temperature
    min_temp: 16
    max_temp: 24
    ac_mode: false
    target_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 15
    precision: 0.1