#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml

sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable telegram bot
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - 10944908 # example id of a user
#      - -987654321  # example id of a group, starts with a -

# enable communication with ARLO devices
# arlo:
#   username: <username>
#   password: <password>

