#################################################################
## Groups
#################################################################

  #################################################################
  ## Interactive Devices
  #################################################################

  christmas_lights:
    name: Christmas Lights
    entities:
      - light.garage_front_channel_1
      - light.garage_front_channel_2

  vacuum:
    name: Vacuum
    entities:
      - vacuum.dusty
      - binary_sensor.dusty_bin_full

  #################################################################
  ## Non interactive devices
  #################################################################

  nas:
    name: Network Attached Storage
    entities:
      - binary_sensor.hookie_ewok_security_status
      - binary_sensor.hookie_ewok_drive_1_below_min_remaining_life
      - binary_sensor.hookie_ewok_drive_1_exceeded_max_bad_sectors
      - sensor.hookie_ewok_drive_1_status
      - sensor.hookie_ewok_volume_1_status
      - sensor.hookie_ewok_volume_1_used_space
      - sensor.hookie_ewok_volume_1_volume_used
      - sensor.hookie_ewok_network_down
      - sensor.hookie_ewok_network_up

  printer:
    name: Printer
    entities:
      - sensor.epson_et_4750_series
      - sensor.epson_et_4750_series_black_ink
      - sensor.epson_et_4750_series_cyan_ink
      - sensor.epson_et_4750_series_magenta_ink
      - sensor.epson_et_4750_series_yellow_ink

  # ethmain:
  #   name: Ethereum Mainnet
  #   entities:
  #     - sensor.syncing # true of false
  #     - sensor.mining # true or false
  #     - sensor.lastblock # integer

  #     - sensor.ethnode_get_balance

  # ethropsten:
  #   name: Ethereum Ropsten
  #   entities:
  #     - sensor.syncing # true of false
  #     - sensor.mining # true or false
  #     - sensor.lastblock # integer

  #     - sensor.ethnode_get_balance

  #################################################################
  ## Network
  #################################################################
  # network:
  #   name: Network
  #   entities:
  #     - sensor.fritz_netmonitor

  #################################################################
  ## Sensors
  #################################################################
  
  temperature:
    name: Temperature
      - sensor.mqtt_bathroom_temperature
      - sensor.mqtt_living_temperature

  humidity:
    name: Humidity
      - sensor.mqtt_bathroom_humidity
      - sensor.mqtt_living_humidity

  dsmr:
    name: Energy Readings
    entities:
      - sensor.power_consumption_phase_l1
      - sensor.power_consumption_phase_l2
      - sensor.power_consumption_phase_l3
      - sensor.voltage_phase_l1
      - sensor.voltage_phase_l2
      - sensor.voltage_phase_l3
      - sensor.current_phase_l1
      - sensor.current_phase_l2
      - sensor.current_phase_l3
      # - sensor.power_production_phase_l1
      # - sensor.power_production_phase_l2
      # - sensor.power_production_phase_l3
      - sensor.hourly_gas_consumption

  #################################################################
  ## Environment
  #################################################################
  environment:
    name: Environment
    entities:
      - sun.sun
      - weather.serenity

  #################################################################
  ## People
  #################################################################
  persons:
    name: Persons
    entities:
      - person.yongshi