  morning_temp_slider:
    name: Morning Temperature
    min: 10
    max: 30
    step: 1
    icon: mdi:thermometer
    unit_of_measurement: '째C'

  afternoon_temp_slider:
    name: Afternoon Temperature
    min: 10
    max: 30
    step: 1
    icon: mdi:thermometer
    unit_of_measurement: '째C'

  evening_temp_slider:
    name: Evening Temperature
    min: 10
    max: 30
    step: 1
    icon: mdi:thermometer
    unit_of_measurement: '째C'

  night_temp_slider:
    name: Night Temperature
    min: 10
    max: 30
    step: 1
    icon: mdi:thermometer
    unit_of_measurement: '째C'
