  
  set_fan_speed_1:
    url: 'http://192.168.178.29:5000/set_speed?speed=1'

  set_fan_speed_2:
    url: 'http://192.168.178.29:5000/set_speed?speed=2'

  set_fan_speed_3:
    url: 'http://192.168.178.29:5000/set_speed?speed=3'

  set_fan_speed_0:
    url: 'http://192.168.178.29:5000/set_speed?speed=0'

  set_fan_speed_auto:
    url: 'http://192.168.178.29:5000/set_speed?speed=9'