
heater_override_0:
  alias: Heater Override Off
  sequence:
  - event: HEATER_OVERRIDE
    event_data:
      status: '0'
  mode: queued
  icon: hass:cancel
  max: 10

heater_override_1:
  alias: Heater_Override_On
  sequence:
  - event: HEATER_OVERRIDE
    event_data:
      status: '1'
  mode: queued
  icon: hass:fire
  max: 10

heater_override_off:
  alias: Heater_Override_Auto
  sequence:
  - event: HEATER_OVERRIDE
    event_data:
      status: '9'
  mode: queued
  icon: hass:refresh
  max: 10

garden_lights_override_on:
  alias: Garden Lights Override On
  sequence:
  - event: GARDEN_LIGHTS_OVERRIDE
    event_data:
      status: 'on'
  mode: queued
  icon: mdi:lightbulb-on
  max: 10

garden_lights_override_off:
  alias: Garden Lights Override Off
  sequence:
  - event: GARDEN_LIGHTS_OVERRIDE
    event_data:
      status: 'off'
  mode: queued
  icon: mdi:lightbulb-off-outline
  max: 10

garden_lights_override_auto:
  alias: Garden Lights Override Auto
  sequence:
  - event: GARDEN_LIGHTS_OVERRIDE
    event_data:
      status: auto
  mode: queued
  icon: mdi:refresh
  max: 10