  # # enable DSMR sensor
  # - platform: dsmr
  #   host: 192.168.178.44
  #   port: 2001
  #   dsmr_version: 5

  #################################################################
  ## Wifi Access Points
  #################################################################
  - platform: snmp
    name: snmp_fritzbox
    host: 192.168.1.1
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

  - platform: snmp
    name: snmp_wifi_eap245
    host: 192.168.1.38
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

  - platform: snmp
    name: snmp_wifi_eap110
    host: 192.168.1.21
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

    # 1.3.6.1.2.1.3.1.1.2
    # 1.3.6.1.2.1.3.1.1.2.16.1
    # 1.3.6.1.2.1.3.1.1.2.19.1

  #################################################################
  ## Afvalwijzer
  #################################################################

  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 8256CT              # (required, default = '')
    street_number:  1                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"


  #################################################################
  ## MQTT Doorbell status
  #################################################################

  - platform: mqtt
    name: mqtt_doorbell_status
    state_topic: 'doorbell/status'

  #################################################################
  ## MQTT Climate sensors
  #################################################################

  - platform: mqtt
    name: mqtt_bathroom_humidity
    state_topic: "bathroom/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_living_humidity
    state_topic: "living/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_bathroom_temperature
    state_topic: "bathroom/temperature"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_living_temperature
    state_topic: "living/temperature"
    unit_of_measurement: '°C'

  #################################################################
  ## MQTT Climate Fan sensors
  #################################################################

  - platform: mqtt
    name: mqtt_fan_status
    state_topic: 'fan/speed'

  # mqtt topic to communicate command to the fan service
  - platform: mqtt
    name: mqtt_fan_set
    state_topic: 'fan/set'
  
  # mqtt topic to communicate a user override via mqtt to the watch_fan in appdaemon
  - platform: mqtt
    name: mqtt_fan_override_set
    state_topic: 'fan/override/set'

  - platform: mqtt
    icon: mdi:fan_alert
    name: mqtt_fan_override_status
    state_topic: 'fan/override/status'

  #################################################################
  ## MQTT Climate Heater sensors
  #################################################################

  - platform: mqtt
    name: mqtt_heater_status
    state_topic: 'heater/status'

  - platform: mqtt
    name: mqtt_thermostat_morning_temp
    state_topic: "thermostat/morning/temp"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_thermostat_afternoon_temp
    state_topic: "thermostat/afternoon/temp"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_thermostat_evening_temp
    state_topic: "thermostat/evening/temp"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_thermostat_night_temp
    state_topic: "thermostat/night/temp"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_thermostat_morning_timeslot_end
    state_topic: "thermostat/morning/timeslot_end"

  - platform: mqtt
    name: mqtt_thermostat_afternoon_timeslot_end
    state_topic: "thermostat/afternoon/timeslot_end"

  - platform: mqtt
    name: mqtt_thermostat_evening_timeslot_end
    state_topic: "thermostat/evening/timeslot_end"

  - platform: mqtt
    name: mqtt_thermostat_night_timeslot_end
    state_topic: "thermostat/night/timeslot_end"

  #################################################################
  ## MQTT DLT nodes
  #################################################################

  - platform: mqtt
    name: mqtt_ethmain_current_block
    state_topic: "ethmain/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_highest_block
    state_topic: "ethmain/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_pulled_states
    state_topic: "ethmain/pulled_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_known_states
    state_topic: "ethmain/known_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_current_block
    state_topic: "ethropsten/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_highest_block
    state_topic: "ethropsten/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_pulled_states
    state_topic: "ethropsten/pulled_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_known_states
    state_topic: "ethropsten/known_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_current_block
    state_topic: "btcmain/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_highest_block
    state_topic: "btcmain/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_connections
    state_topic: "btcmain/connections"
    icon: hass:lan