  # # enable DSMR sensor
  # - platform: dsmr
  #   host: 192.168.178.44
  #   port: 2001
  #   dsmr_version: 5

  #################################################################
  ## Templates
  #################################################################
  - platform: template
    sensors:
        net_energy_use:
            friendly_name: "Net Energy Usage"
            unit_of_measurement: 'kWh'
            value_template: '{{ states("sensor.power_consumption") |float - states("sensor.power_production") | float }}'
        net_energy_production:
            friendly_name: "Net Energy Production"
            unit_of_measurement: 'kWh'
            value_template: '{{ states("sensor.power_production") |float - states("sensor.power_consumption") | float }}'

  #################################################################
  ## Wifi Access Points
  #################################################################
  - platform: snmp
    name: snmp_fritzbox
    host: 192.168.1.1
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

  - platform: snmp
    name: snmp_wifi_eap245
    host: 192.168.1.38
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

  - platform: snmp
    name: snmp_wifi_eap110
    host: 192.168.1.21
    version: 2c
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

    # 1.3.6.1.2.1.3.1.1.2
    # 1.3.6.1.2.1.3.1.1.2.16.1
    # 1.3.6.1.2.1.3.1.1.2.19.1

  #################################################################
  ## Afvalwijzer
  #################################################################

  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 8256CT              # (required, default = '')
    street_number:  1                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"