  # enable DSMR sensor
  - platform: dsmr
    host: 192.168.178.44
    port: 2001
    dsmr_version: 5

  # ------------------ MQTT Climate sensors
  - platform: mqtt
    name: mqtt_bathroom_humidity
    state_topic: "bathroom/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_living_humidity
    state_topic: "living/humidity"
    unit_of_measurement: '%'

  - platform: mqtt
    name: mqtt_bathroom_temperature
    state_topic: "bathroom/temperature"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: mqtt_living_temperature
    state_topic: "living/temperature"
    unit_of_measurement: '°C'

  # ------------------ MQTT Heater and ventilation device status
  - platform: mqtt
    name: mqtt_fan_status
    state_topic: 'fan/speed'

  # mqtt topic to communicate command to the fan service
  - platform: mqtt
    name: mqtt_fan_set
    state_topic: 'fan/set'
  
  # mqtt topic to communicate a user override via mqtt to the watch_fan in appdaemon
  - platform: mqtt
    name: mqtt_fan_override
    state_topic: 'fan/override'

  - platform: mqtt
    name: mqtt_heater_status
    state_topic: 'heater/status'

  # ------------------ MQTT DLT
  - platform: mqtt
    name: mqtt_ethmain_current_block
    state_topic: "ethmain/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_highest_block
    state_topic: "ethmain/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_pulled_states
    state_topic: "ethmain/pulled_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethmain_known_states
    state_topic: "ethmain/known_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_current_block
    state_topic: "ethropsten/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_highest_block
    state_topic: "ethropsten/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_pulled_states
    state_topic: "ethropsten/pulled_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_ethropsten_known_states
    state_topic: "ethropsten/known_states"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_current_block
    state_topic: "btcmain/current_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_highest_block
    state_topic: "btcmain/highest_block"
    icon: hass:lan

  - platform: mqtt
    name: mqtt_btcmain_connections
    state_topic: "btcmain/connections"
    icon: hass:lan
