# https://www.home-assistant.io/integrations/rest/

# enable rest endpoint for ethnode with our account
sensor:
  - platform: rest
    name: ethnode_get_balance
    resource: http://192.168.178.39:5000/get_my_balance
